#!/bin/bash
_nspawn()
{
    local cur prev opts idx first
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    if [ $COMP_CWORD -eq 1 ]; then
        opts=$(nspawn operations)
        COMPREPLY=( $(compgen -W "$opts" -- $cur) )
    else
    first="false"
        for idx in $(nspawn options); do
            if [[ $prev == $idx ]]; then
                first="true"
            fi
        done
        if [[ $first == "false" ]]; then
            opts=$(nspawn list) 
            COMPREPLY=( $(compgen -W "$opts" -- $cur) )
        fi
    fi
}
complete -F _nspawn nspawn
