#!/bin/bash
INSTALL="install"
CLONE="clone"
REMOVE="remove"
START="start"
BOOT="boot"
UPDATE="update"
PACK="pack"
UNPACK="unpack"
CREATE="create"
TEMPLATE="template"
REPOS="oss non-oss debug"
BASEURL="http://download.opensuse.org"
REPOURL="$BASEURL/tumbleweed/repo"
UPDATEREPO="$BASEURL/update/tumbleweed repo-update"
INSTALLSET="patterns-openSUSE-64bit patterns-openSUSE-base zypper rpm"
PATHTO="$PWD"
ACTION=$1
OBJECT=$2

function print_help()
{
    printf "\nError: %0s\n\n" "$1"
    printf "Usage: nspawn-wrapper [ACTION] [OBJECT]\n"
    printf "%0s\n" "Provides a simple wrapper around systemd-nspawn"
    printf "\t%0s\t%20s\n" "ACTION" "The action to perform\n"
    printf "\t\t($INSTALL, $CLONE, $REMOVE, $START, $BOOT, $UPDATE, $PACK, $UNPACK, $CREATE)\n"
    printf "\t%0s\t%20s\n" "OBJECT" "The machine name to interact with"
    printf "\n"
    exit -1
}

function check_exists()
{
    if [ ! -d "$1" ]; then
        echo "Object does not exist"
        exit -1
    fi
}

function check_not_exists()
{
    if [ -d "$1" ]; then
        echo "Object $1 already exists"
        exit -1
    fi
}

if [ $UID -ne 0 ]; then
    printf "\nRestarting script using sudo\n"
    sudo $PWD/nspawn-wrapper $@
    exit $?
fi

if [ -z "$ACTION" ]; then
    print_help "Action is required!"
fi

if [ -z "$OBJECT" ]; then
    print_help "Object is required!"
fi

OBJPATH=$PATHTO/$OBJECT
TARFILE="$OBJECT.tar.gz"
case $ACTION in
$CLONE)
    check_not_exists "$OBJPATH"
    cp -R "$PATHTO/$TEMPLATE" $OBJECT
    ;;
$INSTALL)
    check_exists "$OBJPATH"
    zypper --root $OBJPATH in "${@:3}"
    ;;
$REMOVE)
    check_exists "$OBJPATH"
    rm -r $OBJECT
    ;;
$START)
    check_exists "$OBJPATH"
    systemd-nspawn -D "$OBJECT/"
    ;;
$BOOT)
    check_exists "$OBJPATH"
    systemd-nspawn -b -D "$OBJECT/" -n
    ;;
$UPDATE)
    check_exists "$OBJPATH"
    zypper --root $OBJPATH ref
    zypper --root $OBJPATH up
    ;;
$PACK)
    check_exists "$OBJPATH"
    if [ -e $TARFILE ]; then
        echo "File $TARFILE already exists"
        exit -1
    fi

    tar -cvpzf $TARFILE --one-file-system "$OBJECT/"
    ;;
$UNPACK)
    check_not_exists "$OBJPATH"
    if [ ! -e $TARFILE ]; then
        echo "No tar file found: $TARFILE"
        exit -1
    fi

    tar xzvf $TARFILE
    ;;
$CREATE)
    check_not_exists "$OBJPATH"        
    for repo in $(echo $REPOS); do
        zypper --root $OBJPATH ar -f -c $REPOURL/$repo repo-$repo
    done
    
    zypper --root $OBJPATH ar -f -c $UPDATEREPO
    zypper --root $OBJPATH in $INSTALLSET
    ;;
*)
    print_help "Invalid action: $ACTION"
    ;;
esac
