#!/bin/bash
INSTALL="install"
CLONE="clone"
REMOVE="remove"
START="start"
BOOT="boot"
UPDATE="update"
PACK="pack"
UNPACK="unpack"
REFRESH="refresh"
TEMPLATE="template"
PATHTO="{CONTAINERS}"
ACTION=$1
OBJECT=$2
SCRIPTLOCATION="{PATH_TO_SCRIPT}nspawn"
SHARED_LOCATION="{SHARED}"

if [[ "$OBJECT" == */ ]]; then
    OBJECT=${OBJECT::-1}
fi

function print_help()
{
    printf "\nError: %0s\n\n" "$1"
    printf "Usage: nspawn-wrapper [ACTION] [OBJECT]\n"
    printf "%0s\n" "Provides a simple wrapper around systemd-nspawn"
    printf "\t%0s\t%20s\n" "ACTION" "The action to perform\n"
    printf "\t\t($INSTALL, $CLONE, $REMOVE, $START, $BOOT, $UPDATE, $PACK, $UNPACK, $REFRESH)\n"
    printf "\t%0s\t%20s\n" "OBJECT" "The machine name to interact with"
    printf "\n"
    exit -1
}

function check_exists()
{
    if [ ! -d "$1" ]; then
        echo "Object does not exist"
        exit -1
    fi
}

function check_not_exists()
{
    if [ -d "$1" ]; then
        echo "Object $1 already exists"
        exit -1
    fi
}

# Make X available
xhost +local: > /dev/null 2>&1
if [ $UID -ne 0 ]; then
    printf "\nRestarting script using sudo\n"
    sudo $SCRIPTLOCATION $@
    exit $?
fi

if [ -z "$ACTION" ]; then
    print_help "Action is required!"
fi

if [ "$ACTION" == "$REFRESH" ]; then
    echo "Refreshing all"
    EXIT_CODES=0
    ALL_ITEMS=$(ls $PATHTO)
    for i in ${ALL_ITEMS[*]}; do
        echo -e "\033[0;31m$i\033[0m"
        $SCRIPTLOCATION $UPDATE $i
        if [ $? -ne 0 ]; then
            EXIT_CODES=-1
        fi
    done
    exit $EXIT_CODES
fi

if [ -z "$OBJECT" ]; then
    print_help "Object is required!"
fi

OBJPATH=$PATHTO/$OBJECT
TARFILE="$OBJECT.tar.gz"
case $ACTION in
$CLONE)
    check_not_exists "$OBJPATH"
    cp -R "$PATHTO/$TEMPLATE" $OBJPATH
    ;;
$INSTALL)
    check_exists "$OBJPATH"
    zypper --root $OBJPATH in "${@:3}"
    ;;
$REMOVE)
    check_exists "$OBJPATH"
    rm -r $OBJPATH
    ;;
$START)
    check_exists "$OBJPATH"
    screen -S "$OBJECT" systemd-nspawn -D "$OBJPATH/" -M "$OBJECT" --bind $SHARED_LOCATION "${@:3}"
    ;;
$BOOT)
    check_exists "$OBJPATH"
    screen -S "$OBJECT" systemd-nspawn -b -D "$OBJPATH/" -M "$OBJECT" --bind $SHARED_LOCATION "${@:3}"
    ;;
$UPDATE)
    check_exists "$OBJPATH"
    zypper --root $OBJPATH ref
    zypper --root $OBJPATH up
    ;;
$PACK)
    check_exists "$OBJPATH"
    if [ -e $TARFILE ]; then
        echo "File $TARFILE already exists"
        exit -1
    fi

    tar -cvpzf $TARFILE --one-file-system "$OBJPATH/"
    ;;
$UNPACK)
    check_not_exists "$OBJPATH"
    if [ ! -e $TARFILE ]; then
        echo "No tar file found: $TARFILE"
        exit -1
    fi

    tar xzvf $TARFILE
    ;;
*)
    print_help "Invalid action: $ACTION"
    ;;
esac
